# A Playbook for the installation of WordPress trunk 
# including wp-cli to manage WordPress via the commandline
#

# PHPXRef installeren en runnen! 
# phpMyAdmin installeren
# Vragen om site urls
# Voeg ook WordPress stable toe
# Denk na over directories mounten

---
- hosts: all
  sudo: yes
  tasks: 
  
    - name: Make sure apt-get update has been run 
      apt: update_cache=yes
    
    - name: Make sure my locales (nl_NL.UTF-8) are supported on the guest vm
      command: locale-gen nl_NL.UTF-8
   
    - name: Add vagrant user to www-data group    
      user: name=vagrant groups=www-data append=yes 
    
    - name: install packages 
      apt: pkg={{ item }}
      with_items: 
        - apache2
        - php5
        - php5-mysql
        - php5-xdebug
        - php-pear
        - phpmyadmin
        - git
        - subversion 
        - vim  
        - mysql-server 
        - python-mysqldb

    - name: checkout WordPress trunk (overwrite if exists), this make take a few minutes...
      subversion: repo=http://core.svn.wordpress.org/trunk/ dest=/var/www/wordpress-trunk.dev force=yes

    - name: Create /var/www/wordpress-latest.dev      
      file: path=/var/www/wordpress-latest.dev state=directory mode=0755
    
    - name: Get latest stable version 
      command: wget http://wordpress.org/latest.tar.gz -P /var/www/wordpress-latest.dev/

        # Get WP-CLI see http://wp-cli.org/
    - name: install wp-cli, a command-line interface for WordPress
      command: wget https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    
    - name: make wp-cli executable 
      command: /bin/chmod +x wp-cli.phar

    - name: move wp-cli to /usr/bin/wp
      command: /bin/mv wp-cli.phar /usr/bin/wp


    - name: Untar latest stable WordPress version 
      command: tar -xzv --strip 1 -f /var/www/wordpress-latest.dev/latest.tar.gz -C /var/www/wordpress-latest.dev  

    - name: copy WordPress latest to multi latest  
      command: cp -r /var/www/wordpress-latest.dev /var/www/wordpress-multi-latest.dev

    - name: copy WordPress trunk to multi trunk  
      command: cp -r /var/www/wordpress-trunk.dev /var/www/wordpress-multi-trunk.dev


      # Setup MySQL databases. Each WordPress install gets their own database.
    - name: create wordpress-trunk.dev database
      mysql_db: name=wordpresstrunk state=present

    - name: create wordpress-multi-trunk.dev database
      mysql_db: name=wordpressmultitrunk state=present

    - name: add database user wptrunk
      mysql_user: name=wptrunk password=dbtrunkpwd priv=wordpresstrunk.*:ALL state=present

    - name: add database user wpmultitrunk
      mysql_user: name=wpmultitrunk password=dbtrunkpwd priv=wordpressmultitrunk.*:ALL state=present

    - name: create wordpress-latest.dev database
      mysql_db: name=wordpresslatest state=present

    - name: create wordpress-multi-latest.dev database
      mysql_db: name=wordpressmultilatest state=present

    - name: add database user wplatest
      mysql_user: name=wplatest password=dblatestpwd priv=wordpresslatest.*:ALL state=present

    - name: add database user wpmultilatest
      mysql_user: name=wpmultilatest password=dblatestpwd priv=wordpressmultilatest.*:ALL state=present


      # Apache configuration
      # Apache Virtualhosts' files need to end in *.conf otherwise it will not work with Ubuntu/Debian(?) server 
    - name: activate mod_rewrite
      command: /usr/sbin/a2enmod rewrite
      
    - name: copy virtualhost for WordPress' trunk single install wordpress-trunk.dev. 
      copy: src=wordpress-trunk.dev.conf dest=/etc/apache2/sites-available/wordpress-trunk.dev.conf
      
    - name: copy virtualhost for WordPress Network' trunk install wordpress-multi-trunk.dev
      copy: src=wordpress-multi-trunk.dev.conf dest=/etc/apache2/sites-available/wordpress-multi-trunk.dev.conf

    - name: copy virtualhost for WordPress single' latest stable install wordpress-latest.dev. 
      copy: src=wordpress-latest.dev.conf dest=/etc/apache2/sites-available/wordpress-latest.dev.conf
      
    - name: copy virtualhost for WordPress Network' latest stable install wordpress-multi-latest.dev
      copy: src=wordpress-multi-latest.dev.conf dest=/etc/apache2/sites-available/wordpress-multi-latest.dev.conf

    - name: activate site wordpress-trunk.dev
      command: /usr/sbin/a2ensite wordpress-trunk.dev

    - name: activate site wordpress-multi-trunk.dev
      command: /usr/sbin/a2ensite wordpress-multi-trunk.dev

    - name: activate site wordpress-latest.dev
      command: /usr/sbin/a2ensite wordpress-latest.dev

    - name: activate site wordpress-multi-latest.dev
      command: /usr/sbin/a2ensite wordpress-multi-latest.dev


      # Setup mail catcher to log emails sent by your WordPress installs
    - name: setup logmail, a mail catcher in /tmp
      copy: src=logmail dest=/usr/local/bin/logmail

    - name: make logmail executable    
      command: /bin/chmod +x /usr/local/bin/logmail
        

      # Setup PHP
      # TODO set upload size higher
    - name: fix php sendmail_path to use logmail
      copy: src=mail.ini dest=/etc/php5/apache2/conf.d/mail.ini

    - name: restart Apache
      command: /usr/sbin/service apache2 restart

      # Install WordPress trunk, trunk network install, latest stable and latest stable network install    
    - name: Add WordPress trunk wp-config.php file credentials
      command:  wp core config --allow-root --dbname=wordpresstrunk --dbuser=wptrunk --dbpass=dbtrunkpwd chdir=/var/www/wordpress-trunk.dev

    - name: Add WordPress Network trunk wp-config.php file credentials
      command:  wp core config --allow-root --dbname=wordpressmultitrunk --dbuser=wpmultitrunk --dbpass=dbtrunkpwd chdir=/var/www/wordpress-multi-trunk.dev

    - name: setup WordPress single trunk install  
      command: wp core install --allow-root --url=wordpress-trunk.dev --title=WordPress-Trunk --admin_user=admin --admin_password=admin --admin_email=example@burobjorn.nl chdir=/var/www/wordpress-trunk.dev

    - name: setup WordPress Network trunk install using subdirectories  
      command: wp core multisite-install --allow-root --url=wordpress-multi-trunk.dev --title=WordPress-Multi-Trunk --admin_user=admin --admin_password=admin --admin_email=example@burobjorn.nl chdir=/var/www/wordpress-multi-trunk.dev
        
    - name: Add WordPress latest wp-config.php file credentials
      command:  wp core config --allow-root --dbname=wordpresslatest --dbuser=wplatest --dbpass=dblatestpwd chdir=/var/www/wordpress-latest.dev

    - name: Add WordPress Network latest wp-config.php file credentials
      command:  wp core config --allow-root --dbname=wordpressmultilatest --dbuser=wpmultilatest --dbpass=dblatestpwd chdir=/var/www/wordpress-multi-latest.dev

    - name: setup WordPress single latest install  
      command: wp core install --allow-root --url=wordpress-latest.dev --title=WordPress-latest --admin_user=admin --admin_password=admin --admin_email=example@burobjorn.nl chdir=/var/www/wordpress-latest.dev

    - name: setup WordPress Network latest install using subdirectories  
      command: wp core multisite-install --allow-root --url=wordpress-multi-latest.dev --title=WordPress-Multi-latest --admin_user=admin --admin_password=admin --admin_email=example@burobjorn.nl chdir=/var/www/wordpress-multi-latest.dev

      # Chown directory to allow automatic plugin installs   
    - name: Chown wordPress-trunk/wp-content to www-data:www-data with '0755' permissions
      file: state=directory owner=www-data group=www-data recurse=yes mode=0755 path=/var/www/wordpress-trunk.dev

    - name: Chown wordPress-multi-trunk.dev/wp-content to www-data:www-data with '0755' permissions
      file: state=directory owner=www-data group=www-data recurse=yes mode=0755 path=/var/www/wordpress-multi-trunk.dev
        
    - name: Chown wordPress-latest/wp-content to www-data:www-data with '0755' permissions
      file: state=directory owner=www-data group=www-data recurse=yes mode=0755 path=/var/www/wordpress-latest.dev

    - name: Chown wordPress-multi-latest.dev/wp-content to www-data:www-data with '0755' permissions
      file: state=directory owner=www-data group=www-data recurse=yes mode=0755 path=/var/www/wordpress-multi-latest.dev


